name: ci-ubuntu-latest

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update the system packages
        run: sudo apt-get update

      - name: Install the dependencies
        run: sudo apt-get install -y build-essential pkg-config automake libncurses5-dev autotools-dev libparted-dev libconfig-dev libconfig++-dev dmidecode

      - name: Generate the autogen files
        run: ./autogen.sh

      - name: Configure the program
        run: ./configure CFLAGS='-O0 -g -Wall -Wextra'

      - name: Compile the program
        run: make
